README.md

dhis2 configuration setup using Ansible

feat(Configuration): Ansible config. setup

---

2019/01/21.md

Minute of the discussion (to the best of my ability, please comment if I have misrepresented anything) on Slack 2019-01-21 which dealt with the issue of **Application testing** initiated by @Mohammer5 and contributed to be many.
I found the GDrive document where a summary could be consumed, but I think gathering all minutes with **conclusions** and/or actions for things which affect the Frontend Team should be in a more accessible place than GDrive, and to me that is Git.

Testing discussion from Slack 2019-01-21

---

2019/02/14.md

Raw notes from meeting. Working on cleaning them up.
Closes #11.

Valentine UI-library meeting and feedback session

---

2019/02/24.md

docs: add result of redux discussion

---

decisions/2019/05/25-war-docker-schemes.md

docs: add release scheme documentation

---

decisions/2019/09/12-tapps-workflow-iterations.md

Adding bullet points for the things we discussed.
Pretty sure I forgot one point we talked about, add a comment if you feel there is something missing. I'll add more information about the high-level points tomorrow, quickly writing this down before I forget something else. 🤔

docs: add meeting minute for tapps meeting

---

decisions/2019/11/20-app-shell-design-components.md

Meeting summary, conclusions and next actions.

docs: add app shell design meeting minutes (2019-20-11)

---

decisions/2019/11/11-tapps-meeting-remote-errors-etc.md
decisions/2019/11/tapps-meeting-remote-errors-etc.md

docs: add tapps meeting 2019-11-11 minute

---

decisions/2019/05/25-war-docker-schemes.md

Organise war files into version folders at the highest level.

refactor: revise war scheme a little

---

decisions/2020/02/04-05-tapps-remotes-in-oslo.md

Hi @dhis2/team-apps :wave: 
Sorry about the delay on this. I hope this feels familiar even if it is a reconstruction from my perspective. I've tried to find as many references to the various discussions and decisions as I could. 
Any additions and amendments are welcome, as usual !
Closes #89

docs(tapps): add summary of remote week

---

howto/writing_feature_files.md

Relates to discussion in dhis2/ui-core#823

docs: add howto document for writing feature files

---

decisions/2020/04/15-app-hub-architecture.md

Thank you for a nice meeting and here is the minutes from yesterdays meeting about the App Hub.
Hope I managed to capture all the output. As usual, approve if this aligns with you and request changes if it does not.

docs(apphub): architecture meeting

---

gotchas/cypress-testing.md

Documenting what I found here: https://github.com/dhis2/ui/issues/87

docs(gotcha): add cypress gotcha

---

decisions/2020/11/25-frontend-initiatives.md

docs(2020-11-25): frontend initiatives meeting minutes

---

decisions/2020/11/24-ui-icons.md

Closes https://github.com/dhis2/notes/issues/160
Closes https://github.com/dhis2/notes/issues/158
Closes https://github.com/dhis2/notes/issues/162
Closes https://github.com/dhis2/notes/issues/163
Closes https://github.com/dhis2/notes/issues/175
Closes https://github.com/dhis2/notes/issues/159

docs(2020-11-24): meeting minutes for ui icons

---

decisions/2020/12/09-fe-initiatives-meeting.md

docs(2020-12-09): add minutes for fe meeting

---

decisions/2021/02/03-fe-meeting.md

Closes #202 
Thanks for the meeting everyone, very nice to see demos and show and tells!

docs(2021-02-03): frontend initiatives meeting notes

---

decisions/2021/02/02-team-platform-rota.md

This adds a section with guidance and suggestions on what to do when
on-duty.

docs(2021-02-10): addendum to minutes for rota

---

decisions/2021/03/30-pwa-technical-kickoff.md

docs(2021-03-30): PWA Technical Kickoff meeting

---

decisions/2021/03/18-large-nested-collections.md

Minutes from today's meeting about large nested collections.
Relates to: https://jira.dhis2.org/browse/DHIS2-10699
cc: @amcgee

docs(2021-03-21): large nested collections meeting

---

decisions/2021/04/12-app-hub-meeting.md

docs: add notes from App Hub meeting on April 12, 2021

---

decisions/2021/04/19-app-hub-meeting.md

No agenda, follow-up to previous meeting action items (#255)

docs: add notes from App Hub meeting on April 19, 2021

---

platform/processes/platform-fe-jira.md

Supersedes https://github.com/dhis2/notes/issues/55.

docs: add pfe jira workflow
